import '../services/app_settings_service.dart';

class TxText {
  static String get locale => AppSettingsService.instance.locale;

  static const _strings = <String, Map<String, String>>{
    'tr': {
      'home':'Ana Sayfa','lessons':'Dersler','exams':'Denemeler','stats':'İstatistik','profile':'Profil',
      'choose_country':'Ülke / Sınav Sistemi','choose_language':'Arayüz Dili','choose_content_language':'Ders ve Soru Dili',
      'content_language_help':'Seçtiğin ülkenin derslerini bu dilde okuyabilirsin. Mobilde gerektiğinde ücretsiz cihaz içi çeviri modeli indirilir.',
      'continue':'Devam Et','change_country':'Ülke ve Diller','daily_goal':'Bugünkü Hedefin','day_streak':'Gün Serisi',
      'full_exam':'Tam Deneme Sınavı','start_exam':'Tam Denemeyi Başlat','study_topics':'Ders ders çalış, açıklamaları öğren ve o konudan soru çöz.',
      'quick5':'Hızlı 5','quick10':'Hızlı 10','wrong_book':'Yanlış Defteri','country_pack':'Sınav Paketi',
      'practice_notice':'Sorular TeoriX tarafından hazırlanmış özgün çalışma sorularıdır; resmî soru bankası değildir.',
      'exam_result':'Deneme Sonucu','passed':'Başarılı!','keep_studying':'Biraz daha çalışalım','correct':'Doğru','wrong':'Yanlış','empty':'Boş',
      'change':'Değiştir','language':'Dil','country':'Ülke','save':'Kaydet','cancel':'Vazgeç','delete':'Sil','clear_all':'Tümünü Temizle',
      'mark_all_read':'Tümünü Oku','notifications':'Bildirim Merkezi','no_notifications':'Şimdilik bildirimin yok.',
      'name_title':'Sana nasıl hitap edelim?','name_hint':'Adın veya takma adın','name_help':'Bu isim yalnızca TeoriX içinde sana hitap etmek için kullanılır.',
      'name_required':'Devam etmek için bir isim gir.','welcome':'Hoş geldin','app_language':'Arayüz','study_language':'Ders dili',
      'plan_free':'Free','plan_plus':'Plus','plan_pro':'Pro','one_time':'Tek seferlik','monthly':'Aylık','yearly':'Yıllık',
      'free_features':'Tüm temel dersler + sınırsız Hızlı 5/10 + günde 3 tam deneme + 3 Akıllı Öğretmen kullanımı','plus_features':'Tek seferlik • reklamsız + tam tabela oyunu + günde 6 tam deneme + 8 Akıllı Öğretmen kullanımı',
      'pro_features':'Plus + sınırsız tam deneme + kişiye özel deneme + gelişmiş analiz + sınırsız hazır Akıllı Öğretmen + Son 48 Saat',
      'restore_purchases':'Satın Alımları Geri Yükle','manage_membership':'Üyelik ve Satın Alımlar','ad_preferences':'Reklam Tercihleri',
      'cloud_progress':'İlerleme ve Hesap','study_reminders':'Çalışma Hatırlatıcıları','exam_plan':'Sınav Planım','history':'Geçmiş',
      'smart_teacher':'Akıllı Öğretmen','reward_ai':'Reklam İzle • +1 Akıllı Açıklama','reward_exam':'Reklam İzle • +1 Tam Deneme',
      'basic_explanation_free':'Temel açıklama her zaman ücretsizdir.','pro_required':'Bu özellik TeoriX Pro ile açılır.',
      'web_translation_note':'Chrome geliştirme önizlemesinde ders metni kaynak dilde kalabilir. Android/iOS sürümünde cihaz içi çeviri kullanılabilir.',
      'download_translation':'Çeviri Dilini Hazırla','translation_ready':'Çeviri modeli hazır.','translation_failed':'Çeviri modeli indirilemedi. İnternet bağlantını kontrol et.',
      'hazard_note':'Bu pakette gerçek sınavın tehlike algısı/video bölümü ayrı değerlendirilir.',
      'sign_in':'Hesabımı Koru','sign_out':'Çıkış Yap','guest':'Misafir','edit_name':'Adımı Değiştir',
      'pricing_note':'Gerçek fiyatlar mağazadan ve bulunduğun ülkenin para biriminden alınır.',
    },
    'nl': {
      'home':'Home','lessons':'Lessen','exams':'Examens','stats':'Statistieken','profile':'Profiel',
      'choose_country':'Land / Examensysteem','choose_language':'Interfacetaal','choose_content_language':'Taal van lessen en vragen',
      'content_language_help':'Je kunt de lessen van het gekozen land in deze taal lezen. Op mobiel kan zo nodig gratis een vertaalmodel op het apparaat worden gedownload.',
      'continue':'Doorgaan','change_country':'Land en talen','daily_goal':'Doel van vandaag','day_streak':'Dagenreeks',
      'full_exam':'Volledig theorie-examen','start_exam':'Start volledig examen','study_topics':'Leer les voor les, lees de uitleg en oefen daarna met vragen.',
      'quick5':'Snel 5','quick10':'Snel 10','wrong_book':'Foutenboek','country_pack':'Examenpakket',
      'practice_notice':'De vragen zijn originele TeoriX-oefenvragen en geen officiële examenvragen.',
      'exam_result':'Examenresultaat','passed':'Geslaagd!','keep_studying':'Nog even oefenen','correct':'Goed','wrong':'Fout','empty':'Leeg',
      'change':'Wijzigen','language':'Taal','country':'Land','save':'Opslaan','cancel':'Annuleren','delete':'Verwijderen','clear_all':'Alles wissen',
      'mark_all_read':'Alles gelezen','notifications':'Meldingen','no_notifications':'Je hebt nu geen meldingen.',
      'name_title':'Hoe mogen we je noemen?','name_hint':'Naam of bijnaam','name_help':'Deze naam wordt alleen in TeoriX gebruikt om je aan te spreken.',
      'name_required':'Vul een naam in om door te gaan.','welcome':'Welkom','app_language':'Interface','study_language':'Lestaal',
      'plan_free':'Free','plan_plus':'Plus','plan_pro':'Pro','one_time':'Eenmalig','monthly':'Maandelijks','yearly':'Jaarlijks',
      'free_features':'Alle basislessen + onbeperkt Snel 5/10 + 3 volledige examens + 3 Slimme-Leraar-gebruiken per dag','plus_features':'Eenmalig • geen advertenties + volledig bordenspel + 6 volledige examens + 8 Slimme-Leraar-gebruiken per dag',
      'pro_features':'Plus + onbeperkte volledige examens + persoonlijke tests + uitgebreide analyse + onbeperkte voorbereide Slimme Leraar + Laatste 48 Uur',
      'restore_purchases':'Aankopen herstellen','manage_membership':'Abonnement en aankopen','ad_preferences':'Advertentievoorkeuren',
      'cloud_progress':'Voortgang en account','study_reminders':'Studieherinneringen','exam_plan':'Mijn examenplan','history':'Geschiedenis',
      'smart_teacher':'Slimme Leraar','reward_ai':'Bekijk advertentie • +1 slimme uitleg','reward_exam':'Bekijk advertentie • +1 volledig examen',
      'basic_explanation_free':'Basisuitleg is altijd gratis.','pro_required':'Deze functie is beschikbaar met TeoriX Pro.',
      'web_translation_note':'In de Chrome-ontwikkelpreview kan cursusinhoud in de brontaal blijven. Op Android/iOS kan vertaling op het apparaat worden gebruikt.',
      'download_translation':'Vertaaltaal voorbereiden','translation_ready':'Vertaalmodel is klaar.','translation_failed':'Vertaalmodel kon niet worden gedownload. Controleer je internetverbinding.',
      'hazard_note':'Bij dit pakket wordt het echte gevaarherkennings-/videodeel apart beoordeeld.',
      'sign_in':'Account beveiligen','sign_out':'Uitloggen','guest':'Gast','edit_name':'Naam wijzigen',
      'pricing_note':'Werkelijke prijzen worden uit de store en in je lokale valuta geladen.',
    },
    'de': {
      'home':'Start','lessons':'Lernen','exams':'Prüfungen','stats':'Statistik','profile':'Profil',
      'choose_country':'Land / Prüfungssystem','choose_language':'Oberflächensprache','choose_content_language':'Sprache für Lektionen und Fragen',
      'content_language_help':'Du kannst die Inhalte des gewählten Landes in dieser Sprache lesen. Auf Mobilgeräten kann bei Bedarf kostenlos ein Übersetzungsmodell auf dem Gerät geladen werden.',
      'continue':'Weiter','change_country':'Land und Sprachen','daily_goal':'Heutiges Ziel','day_streak':'Tages-Serie',
      'full_exam':'Theorieprüfung Simulation','start_exam':'Prüfung starten','study_topics':'Lerne Lektion für Lektion und übe danach passende Fragen.',
      'quick5':'Schnell 5','quick10':'Schnell 10','wrong_book':'Fehlerheft','country_pack':'Prüfungspaket',
      'practice_notice':'Alle Fragen sind eigene TeoriX-Übungsfragen und keine amtlichen Prüfungsfragen.',
      'exam_result':'Prüfungsergebnis','passed':'Bestanden!','keep_studying':'Noch etwas üben','correct':'Richtig','wrong':'Falsch','empty':'Leer',
      'change':'Ändern','language':'Sprache','country':'Land','save':'Speichern','cancel':'Abbrechen','delete':'Löschen','clear_all':'Alles löschen',
      'mark_all_read':'Alle gelesen','notifications':'Mitteilungen','no_notifications':'Zurzeit gibt es keine Mitteilungen.',
      'name_title':'Wie sollen wir dich nennen?','name_hint':'Name oder Spitzname','name_help':'Dieser Name wird nur in TeoriX verwendet, um dich anzusprechen.',
      'name_required':'Gib einen Namen ein, um fortzufahren.','welcome':'Willkommen','app_language':'Oberfläche','study_language':'Lernsprache',
      'plan_free':'Free','plan_plus':'Plus','plan_pro':'Pro','one_time':'Einmalig','monthly':'Monatlich','yearly':'Jährlich',
      'free_features':'Alle Grundlektionen + unbegrenzt Schnell 5/10 + 3 vollständige Prüfungen + 3 Smarter-Lehrer-Nutzungen pro Tag','plus_features':'Einmalig • werbefrei + komplettes Zeichen-Spiel + 6 vollständige Prüfungen + 8 Smarter-Lehrer-Nutzungen pro Tag',
      'pro_features':'Plus + unbegrenzte vollständige Prüfungen + persönliche Tests + erweiterte Analyse + unbegrenzt vorbereiteter Smarter Lehrer + Letzte 48 Stunden',
      'restore_purchases':'Käufe wiederherstellen','manage_membership':'Mitgliedschaft und Käufe','ad_preferences':'Werbeeinstellungen',
      'cloud_progress':'Fortschritt und Konto','study_reminders':'Lernerinnerungen','exam_plan':'Mein Prüfungsplan','history':'Verlauf',
      'smart_teacher':'Smarter Lehrer','reward_ai':'Werbung ansehen • +1 smarte Erklärung','reward_exam':'Werbung ansehen • +1 vollständige Prüfung',
      'basic_explanation_free':'Die grundlegende Erklärung ist immer kostenlos.','pro_required':'Diese Funktion ist mit TeoriX Pro verfügbar.',
      'web_translation_note':'In der Chrome-Entwicklungsvorschau können Kursinhalte in der Quellsprache bleiben. Auf Android/iOS ist Übersetzung auf dem Gerät möglich.',
      'download_translation':'Übersetzung vorbereiten','translation_ready':'Übersetzungsmodell ist bereit.','translation_failed':'Übersetzungsmodell konnte nicht geladen werden. Prüfe deine Internetverbindung.',
      'hazard_note':'Bei diesem Paket wird der echte Gefahrenwahrnehmungs-/Videoteil separat bewertet.',
      'sign_in':'Konto sichern','sign_out':'Abmelden','guest':'Gast','edit_name':'Name ändern',
      'pricing_note':'Tatsächliche Preise werden aus dem Store in deiner lokalen Währung geladen.',
    },
    'en': {
      'home':'Home','lessons':'Lessons','exams':'Practice','stats':'Stats','profile':'Profile',
      'choose_country':'Country / Test System','choose_language':'Interface Language','choose_content_language':'Lesson & Question Language',
      'content_language_help':'You can study the selected country in this language. On mobile, a free on-device translation model can be downloaded when needed.',
      'continue':'Continue','change_country':'Country & Languages','daily_goal':'Today’s Goal','day_streak':'Day Streak',
      'full_exam':'Full Knowledge Test','start_exam':'Start Full Test','study_topics':'Study lesson by lesson, learn the explanation, then practice that topic.',
      'quick5':'Quick 5','quick10':'Quick 10','wrong_book':'Mistake Book','country_pack':'Test Pack',
      'practice_notice':'Questions are original TeoriX practice items and are not official test questions.',
      'exam_result':'Test Result','passed':'Passed!','keep_studying':'Keep studying','correct':'Correct','wrong':'Wrong','empty':'Blank',
      'change':'Change','language':'Language','country':'Country','save':'Save','cancel':'Cancel','delete':'Delete','clear_all':'Clear All',
      'mark_all_read':'Mark all read','notifications':'Notification Center','no_notifications':'You have no notifications right now.',
      'name_title':'What should we call you?','name_hint':'Name or nickname','name_help':'This name is only used inside TeoriX to address you.',
      'name_required':'Enter a name to continue.','welcome':'Welcome','app_language':'Interface','study_language':'Study language',
      'plan_free':'Free','plan_plus':'Plus','plan_pro':'Pro','one_time':'One-time','monthly':'Monthly','yearly':'Yearly',
      'free_features':'All core lessons + unlimited Quick 5/10 + 3 full tests + 3 Smart Teacher uses per day','plus_features':'One-time • no ads + full sign game + 6 full tests + 8 Smart Teacher uses per day',
      'pro_features':'Plus + unlimited full tests + personal tests + advanced analysis + unlimited prepared Smart Teacher + Final 48 Hours',
      'restore_purchases':'Restore Purchases','manage_membership':'Membership & Purchases','ad_preferences':'Ad Preferences',
      'cloud_progress':'Progress & Account','study_reminders':'Study Reminders','exam_plan':'My Test Plan','history':'History',
      'smart_teacher':'Smart Teacher','reward_ai':'Watch Ad • +1 Smart Explanation','reward_exam':'Watch Ad • +1 Full Test',
      'basic_explanation_free':'Basic explanations are always free.','pro_required':'This feature is available with TeoriX Pro.',
      'web_translation_note':'In the Chrome development preview, course content may remain in its source language. Android/iOS can use on-device translation.',
      'download_translation':'Prepare Translation Language','translation_ready':'Translation model is ready.','translation_failed':'Translation model could not be downloaded. Check your internet connection.',
      'hazard_note':'The real test evaluates its hazard-perception/video part separately for this pack.',
      'sign_in':'Protect My Account','sign_out':'Sign Out','guest':'Guest','edit_name':'Change Name',
      'pricing_note':'Actual prices are loaded from the store in your local currency.',
    },
  };

  static String t(String key) => forLocale(key, locale);

  static String forLocale(String key, String code) =>
      _strings[code]?[key] ?? _strings['en']?[key] ?? key;

  static String pick(String tr, String nl, String de, String en) => switch (locale) {
        'tr' => tr,
        'nl' => nl,
        'de' => de,
        _ => en,
      };

  static String languageName(String code) => switch (code) {
        'tr' => 'Türkçe',
        'nl' => 'Nederlands',
        'de' => 'Deutsch',
        'en' => 'English',
        _ => code.toUpperCase(),
      };
}
